/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as LayoutProfileRouteImport } from './routes/_layout/profile'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutUsersRouteRouteImport } from './routes/_layout/users/route'
import { Route as LayoutRoomsRouteRouteImport } from './routes/_layout/rooms/route'
import { Route as LayoutBookingsRouteRouteImport } from './routes/_layout/bookings/route'
import { Route as LayoutUsersIndexRouteImport } from './routes/_layout/users/index'
import { Route as LayoutRoomsIndexRouteImport } from './routes/_layout/rooms/index'
import { Route as LayoutBookingsIndexRouteImport } from './routes/_layout/bookings/index'
import { Route as LayoutUsersAddRouteImport } from './routes/_layout/users/add'
import { Route as LayoutUsersUserIdRouteImport } from './routes/_layout/users/$userId'
import { Route as LayoutRoomsAddRouteImport } from './routes/_layout/rooms/add'
import { Route as LayoutRoomsRoomIdRouteImport } from './routes/_layout/rooms/$roomId'
import { Route as LayoutBookingsMyRouteImport } from './routes/_layout/bookings/my'
import { Route as LayoutBookingsCalendarRouteImport } from './routes/_layout/bookings/calendar'
import { Route as LayoutBookingsApprovalsRouteImport } from './routes/_layout/bookings/approvals'
import { Route as LayoutBookingsAddRouteImport } from './routes/_layout/bookings/add'
import { Route as LayoutBookingsBookingIdRouteImport } from './routes/_layout/bookings/$bookingId'
import { Route as LayoutUsersUserIdIndexRouteImport } from './routes/_layout/users/$userId.index'
import { Route as LayoutRoomsRoomIdIndexRouteImport } from './routes/_layout/rooms/$roomId.index'
import { Route as LayoutUsersUserIdEditRouteImport } from './routes/_layout/users/$userId.edit'
import { Route as LayoutRoomsRoomIdHistoryRouteImport } from './routes/_layout/rooms/$roomId.history'
import { Route as LayoutRoomsRoomIdEditRouteImport } from './routes/_layout/rooms/$roomId.edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutProfileRoute = LayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersRouteRoute = LayoutUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRoomsRouteRoute = LayoutRoomsRouteRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBookingsRouteRoute = LayoutBookingsRouteRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersIndexRoute = LayoutUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutUsersRouteRoute,
} as any)
const LayoutRoomsIndexRoute = LayoutRoomsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoomsRouteRoute,
} as any)
const LayoutBookingsIndexRoute = LayoutBookingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutBookingsRouteRoute,
} as any)
const LayoutUsersAddRoute = LayoutUsersAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => LayoutUsersRouteRoute,
} as any)
const LayoutUsersUserIdRoute = LayoutUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => LayoutUsersRouteRoute,
} as any)
const LayoutRoomsAddRoute = LayoutRoomsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => LayoutRoomsRouteRoute,
} as any)
const LayoutRoomsRoomIdRoute = LayoutRoomsRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => LayoutRoomsRouteRoute,
} as any)
const LayoutBookingsMyRoute = LayoutBookingsMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => LayoutBookingsRouteRoute,
} as any)
const LayoutBookingsCalendarRoute = LayoutBookingsCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => LayoutBookingsRouteRoute,
} as any)
const LayoutBookingsApprovalsRoute = LayoutBookingsApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => LayoutBookingsRouteRoute,
} as any)
const LayoutBookingsAddRoute = LayoutBookingsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => LayoutBookingsRouteRoute,
} as any)
const LayoutBookingsBookingIdRoute = LayoutBookingsBookingIdRouteImport.update({
  id: '/$bookingId',
  path: '/$bookingId',
  getParentRoute: () => LayoutBookingsRouteRoute,
} as any)
const LayoutUsersUserIdIndexRoute = LayoutUsersUserIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutUsersUserIdRoute,
} as any)
const LayoutRoomsRoomIdIndexRoute = LayoutRoomsRoomIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoomsRoomIdRoute,
} as any)
const LayoutUsersUserIdEditRoute = LayoutUsersUserIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => LayoutUsersUserIdRoute,
} as any)
const LayoutRoomsRoomIdHistoryRoute =
  LayoutRoomsRoomIdHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => LayoutRoomsRoomIdRoute,
  } as any)
const LayoutRoomsRoomIdEditRoute = LayoutRoomsRoomIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => LayoutRoomsRoomIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/bookings': typeof LayoutBookingsRouteRouteWithChildren
  '/rooms': typeof LayoutRoomsRouteRouteWithChildren
  '/users': typeof LayoutUsersRouteRouteWithChildren
  '/dashboard': typeof LayoutDashboardRoute
  '/profile': typeof LayoutProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/bookings/$bookingId': typeof LayoutBookingsBookingIdRoute
  '/bookings/add': typeof LayoutBookingsAddRoute
  '/bookings/approvals': typeof LayoutBookingsApprovalsRoute
  '/bookings/calendar': typeof LayoutBookingsCalendarRoute
  '/bookings/my': typeof LayoutBookingsMyRoute
  '/rooms/$roomId': typeof LayoutRoomsRoomIdRouteWithChildren
  '/rooms/add': typeof LayoutRoomsAddRoute
  '/users/$userId': typeof LayoutUsersUserIdRouteWithChildren
  '/users/add': typeof LayoutUsersAddRoute
  '/bookings/': typeof LayoutBookingsIndexRoute
  '/rooms/': typeof LayoutRoomsIndexRoute
  '/users/': typeof LayoutUsersIndexRoute
  '/rooms/$roomId/edit': typeof LayoutRoomsRoomIdEditRoute
  '/rooms/$roomId/history': typeof LayoutRoomsRoomIdHistoryRoute
  '/users/$userId/edit': typeof LayoutUsersUserIdEditRoute
  '/rooms/$roomId/': typeof LayoutRoomsRoomIdIndexRoute
  '/users/$userId/': typeof LayoutUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/profile': typeof LayoutProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof LayoutIndexRoute
  '/bookings/$bookingId': typeof LayoutBookingsBookingIdRoute
  '/bookings/add': typeof LayoutBookingsAddRoute
  '/bookings/approvals': typeof LayoutBookingsApprovalsRoute
  '/bookings/calendar': typeof LayoutBookingsCalendarRoute
  '/bookings/my': typeof LayoutBookingsMyRoute
  '/rooms/add': typeof LayoutRoomsAddRoute
  '/users/add': typeof LayoutUsersAddRoute
  '/bookings': typeof LayoutBookingsIndexRoute
  '/rooms': typeof LayoutRoomsIndexRoute
  '/users': typeof LayoutUsersIndexRoute
  '/rooms/$roomId/edit': typeof LayoutRoomsRoomIdEditRoute
  '/rooms/$roomId/history': typeof LayoutRoomsRoomIdHistoryRoute
  '/users/$userId/edit': typeof LayoutUsersUserIdEditRoute
  '/rooms/$roomId': typeof LayoutRoomsRoomIdIndexRoute
  '/users/$userId': typeof LayoutUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_layout/bookings': typeof LayoutBookingsRouteRouteWithChildren
  '/_layout/rooms': typeof LayoutRoomsRouteRouteWithChildren
  '/_layout/users': typeof LayoutUsersRouteRouteWithChildren
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/profile': typeof LayoutProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/bookings/$bookingId': typeof LayoutBookingsBookingIdRoute
  '/_layout/bookings/add': typeof LayoutBookingsAddRoute
  '/_layout/bookings/approvals': typeof LayoutBookingsApprovalsRoute
  '/_layout/bookings/calendar': typeof LayoutBookingsCalendarRoute
  '/_layout/bookings/my': typeof LayoutBookingsMyRoute
  '/_layout/rooms/$roomId': typeof LayoutRoomsRoomIdRouteWithChildren
  '/_layout/rooms/add': typeof LayoutRoomsAddRoute
  '/_layout/users/$userId': typeof LayoutUsersUserIdRouteWithChildren
  '/_layout/users/add': typeof LayoutUsersAddRoute
  '/_layout/bookings/': typeof LayoutBookingsIndexRoute
  '/_layout/rooms/': typeof LayoutRoomsIndexRoute
  '/_layout/users/': typeof LayoutUsersIndexRoute
  '/_layout/rooms/$roomId/edit': typeof LayoutRoomsRoomIdEditRoute
  '/_layout/rooms/$roomId/history': typeof LayoutRoomsRoomIdHistoryRoute
  '/_layout/users/$userId/edit': typeof LayoutUsersUserIdEditRoute
  '/_layout/rooms/$roomId/': typeof LayoutRoomsRoomIdIndexRoute
  '/_layout/users/$userId/': typeof LayoutUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/bookings'
    | '/rooms'
    | '/users'
    | '/dashboard'
    | '/profile'
    | '/auth/callback'
    | '/bookings/$bookingId'
    | '/bookings/add'
    | '/bookings/approvals'
    | '/bookings/calendar'
    | '/bookings/my'
    | '/rooms/$roomId'
    | '/rooms/add'
    | '/users/$userId'
    | '/users/add'
    | '/bookings/'
    | '/rooms/'
    | '/users/'
    | '/rooms/$roomId/edit'
    | '/rooms/$roomId/history'
    | '/users/$userId/edit'
    | '/rooms/$roomId/'
    | '/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard'
    | '/profile'
    | '/auth/callback'
    | '/'
    | '/bookings/$bookingId'
    | '/bookings/add'
    | '/bookings/approvals'
    | '/bookings/calendar'
    | '/bookings/my'
    | '/rooms/add'
    | '/users/add'
    | '/bookings'
    | '/rooms'
    | '/users'
    | '/rooms/$roomId/edit'
    | '/rooms/$roomId/history'
    | '/users/$userId/edit'
    | '/rooms/$roomId'
    | '/users/$userId'
  id:
    | '__root__'
    | '/_layout'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_layout/bookings'
    | '/_layout/rooms'
    | '/_layout/users'
    | '/_layout/dashboard'
    | '/_layout/profile'
    | '/auth/callback'
    | '/_layout/'
    | '/_layout/bookings/$bookingId'
    | '/_layout/bookings/add'
    | '/_layout/bookings/approvals'
    | '/_layout/bookings/calendar'
    | '/_layout/bookings/my'
    | '/_layout/rooms/$roomId'
    | '/_layout/rooms/add'
    | '/_layout/users/$userId'
    | '/_layout/users/add'
    | '/_layout/bookings/'
    | '/_layout/rooms/'
    | '/_layout/users/'
    | '/_layout/rooms/$roomId/edit'
    | '/_layout/rooms/$roomId/history'
    | '/_layout/users/$userId/edit'
    | '/_layout/rooms/$roomId/'
    | '/_layout/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users': {
      id: '/_layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rooms': {
      id: '/_layout/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof LayoutRoomsRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/bookings': {
      id: '/_layout/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof LayoutBookingsRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users/': {
      id: '/_layout/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof LayoutUsersIndexRouteImport
      parentRoute: typeof LayoutUsersRouteRoute
    }
    '/_layout/rooms/': {
      id: '/_layout/rooms/'
      path: '/'
      fullPath: '/rooms/'
      preLoaderRoute: typeof LayoutRoomsIndexRouteImport
      parentRoute: typeof LayoutRoomsRouteRoute
    }
    '/_layout/bookings/': {
      id: '/_layout/bookings/'
      path: '/'
      fullPath: '/bookings/'
      preLoaderRoute: typeof LayoutBookingsIndexRouteImport
      parentRoute: typeof LayoutBookingsRouteRoute
    }
    '/_layout/users/add': {
      id: '/_layout/users/add'
      path: '/add'
      fullPath: '/users/add'
      preLoaderRoute: typeof LayoutUsersAddRouteImport
      parentRoute: typeof LayoutUsersRouteRoute
    }
    '/_layout/users/$userId': {
      id: '/_layout/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof LayoutUsersUserIdRouteImport
      parentRoute: typeof LayoutUsersRouteRoute
    }
    '/_layout/rooms/add': {
      id: '/_layout/rooms/add'
      path: '/add'
      fullPath: '/rooms/add'
      preLoaderRoute: typeof LayoutRoomsAddRouteImport
      parentRoute: typeof LayoutRoomsRouteRoute
    }
    '/_layout/rooms/$roomId': {
      id: '/_layout/rooms/$roomId'
      path: '/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof LayoutRoomsRoomIdRouteImport
      parentRoute: typeof LayoutRoomsRouteRoute
    }
    '/_layout/bookings/my': {
      id: '/_layout/bookings/my'
      path: '/my'
      fullPath: '/bookings/my'
      preLoaderRoute: typeof LayoutBookingsMyRouteImport
      parentRoute: typeof LayoutBookingsRouteRoute
    }
    '/_layout/bookings/calendar': {
      id: '/_layout/bookings/calendar'
      path: '/calendar'
      fullPath: '/bookings/calendar'
      preLoaderRoute: typeof LayoutBookingsCalendarRouteImport
      parentRoute: typeof LayoutBookingsRouteRoute
    }
    '/_layout/bookings/approvals': {
      id: '/_layout/bookings/approvals'
      path: '/approvals'
      fullPath: '/bookings/approvals'
      preLoaderRoute: typeof LayoutBookingsApprovalsRouteImport
      parentRoute: typeof LayoutBookingsRouteRoute
    }
    '/_layout/bookings/add': {
      id: '/_layout/bookings/add'
      path: '/add'
      fullPath: '/bookings/add'
      preLoaderRoute: typeof LayoutBookingsAddRouteImport
      parentRoute: typeof LayoutBookingsRouteRoute
    }
    '/_layout/bookings/$bookingId': {
      id: '/_layout/bookings/$bookingId'
      path: '/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof LayoutBookingsBookingIdRouteImport
      parentRoute: typeof LayoutBookingsRouteRoute
    }
    '/_layout/users/$userId/': {
      id: '/_layout/users/$userId/'
      path: '/'
      fullPath: '/users/$userId/'
      preLoaderRoute: typeof LayoutUsersUserIdIndexRouteImport
      parentRoute: typeof LayoutUsersUserIdRoute
    }
    '/_layout/rooms/$roomId/': {
      id: '/_layout/rooms/$roomId/'
      path: '/'
      fullPath: '/rooms/$roomId/'
      preLoaderRoute: typeof LayoutRoomsRoomIdIndexRouteImport
      parentRoute: typeof LayoutRoomsRoomIdRoute
    }
    '/_layout/users/$userId/edit': {
      id: '/_layout/users/$userId/edit'
      path: '/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof LayoutUsersUserIdEditRouteImport
      parentRoute: typeof LayoutUsersUserIdRoute
    }
    '/_layout/rooms/$roomId/history': {
      id: '/_layout/rooms/$roomId/history'
      path: '/history'
      fullPath: '/rooms/$roomId/history'
      preLoaderRoute: typeof LayoutRoomsRoomIdHistoryRouteImport
      parentRoute: typeof LayoutRoomsRoomIdRoute
    }
    '/_layout/rooms/$roomId/edit': {
      id: '/_layout/rooms/$roomId/edit'
      path: '/edit'
      fullPath: '/rooms/$roomId/edit'
      preLoaderRoute: typeof LayoutRoomsRoomIdEditRouteImport
      parentRoute: typeof LayoutRoomsRoomIdRoute
    }
  }
}

interface LayoutBookingsRouteRouteChildren {
  LayoutBookingsBookingIdRoute: typeof LayoutBookingsBookingIdRoute
  LayoutBookingsAddRoute: typeof LayoutBookingsAddRoute
  LayoutBookingsApprovalsRoute: typeof LayoutBookingsApprovalsRoute
  LayoutBookingsCalendarRoute: typeof LayoutBookingsCalendarRoute
  LayoutBookingsMyRoute: typeof LayoutBookingsMyRoute
  LayoutBookingsIndexRoute: typeof LayoutBookingsIndexRoute
}

const LayoutBookingsRouteRouteChildren: LayoutBookingsRouteRouteChildren = {
  LayoutBookingsBookingIdRoute: LayoutBookingsBookingIdRoute,
  LayoutBookingsAddRoute: LayoutBookingsAddRoute,
  LayoutBookingsApprovalsRoute: LayoutBookingsApprovalsRoute,
  LayoutBookingsCalendarRoute: LayoutBookingsCalendarRoute,
  LayoutBookingsMyRoute: LayoutBookingsMyRoute,
  LayoutBookingsIndexRoute: LayoutBookingsIndexRoute,
}

const LayoutBookingsRouteRouteWithChildren =
  LayoutBookingsRouteRoute._addFileChildren(LayoutBookingsRouteRouteChildren)

interface LayoutRoomsRoomIdRouteChildren {
  LayoutRoomsRoomIdEditRoute: typeof LayoutRoomsRoomIdEditRoute
  LayoutRoomsRoomIdHistoryRoute: typeof LayoutRoomsRoomIdHistoryRoute
  LayoutRoomsRoomIdIndexRoute: typeof LayoutRoomsRoomIdIndexRoute
}

const LayoutRoomsRoomIdRouteChildren: LayoutRoomsRoomIdRouteChildren = {
  LayoutRoomsRoomIdEditRoute: LayoutRoomsRoomIdEditRoute,
  LayoutRoomsRoomIdHistoryRoute: LayoutRoomsRoomIdHistoryRoute,
  LayoutRoomsRoomIdIndexRoute: LayoutRoomsRoomIdIndexRoute,
}

const LayoutRoomsRoomIdRouteWithChildren =
  LayoutRoomsRoomIdRoute._addFileChildren(LayoutRoomsRoomIdRouteChildren)

interface LayoutRoomsRouteRouteChildren {
  LayoutRoomsRoomIdRoute: typeof LayoutRoomsRoomIdRouteWithChildren
  LayoutRoomsAddRoute: typeof LayoutRoomsAddRoute
  LayoutRoomsIndexRoute: typeof LayoutRoomsIndexRoute
}

const LayoutRoomsRouteRouteChildren: LayoutRoomsRouteRouteChildren = {
  LayoutRoomsRoomIdRoute: LayoutRoomsRoomIdRouteWithChildren,
  LayoutRoomsAddRoute: LayoutRoomsAddRoute,
  LayoutRoomsIndexRoute: LayoutRoomsIndexRoute,
}

const LayoutRoomsRouteRouteWithChildren =
  LayoutRoomsRouteRoute._addFileChildren(LayoutRoomsRouteRouteChildren)

interface LayoutUsersUserIdRouteChildren {
  LayoutUsersUserIdEditRoute: typeof LayoutUsersUserIdEditRoute
  LayoutUsersUserIdIndexRoute: typeof LayoutUsersUserIdIndexRoute
}

const LayoutUsersUserIdRouteChildren: LayoutUsersUserIdRouteChildren = {
  LayoutUsersUserIdEditRoute: LayoutUsersUserIdEditRoute,
  LayoutUsersUserIdIndexRoute: LayoutUsersUserIdIndexRoute,
}

const LayoutUsersUserIdRouteWithChildren =
  LayoutUsersUserIdRoute._addFileChildren(LayoutUsersUserIdRouteChildren)

interface LayoutUsersRouteRouteChildren {
  LayoutUsersUserIdRoute: typeof LayoutUsersUserIdRouteWithChildren
  LayoutUsersAddRoute: typeof LayoutUsersAddRoute
  LayoutUsersIndexRoute: typeof LayoutUsersIndexRoute
}

const LayoutUsersRouteRouteChildren: LayoutUsersRouteRouteChildren = {
  LayoutUsersUserIdRoute: LayoutUsersUserIdRouteWithChildren,
  LayoutUsersAddRoute: LayoutUsersAddRoute,
  LayoutUsersIndexRoute: LayoutUsersIndexRoute,
}

const LayoutUsersRouteRouteWithChildren =
  LayoutUsersRouteRoute._addFileChildren(LayoutUsersRouteRouteChildren)

interface LayoutRouteChildren {
  LayoutBookingsRouteRoute: typeof LayoutBookingsRouteRouteWithChildren
  LayoutRoomsRouteRoute: typeof LayoutRoomsRouteRouteWithChildren
  LayoutUsersRouteRoute: typeof LayoutUsersRouteRouteWithChildren
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutProfileRoute: typeof LayoutProfileRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBookingsRouteRoute: LayoutBookingsRouteRouteWithChildren,
  LayoutRoomsRouteRoute: LayoutRoomsRouteRouteWithChildren,
  LayoutUsersRouteRoute: LayoutUsersRouteRouteWithChildren,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutProfileRoute: LayoutProfileRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
