/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as LayoutRoomsRouteImport } from './routes/_layout.rooms'
import { Route as LayoutRoomsIndexRouteImport } from './routes/_layout.rooms.index'
import { Route as LayoutBookingsIndexRouteImport } from './routes/_layout.bookings.index'
import { Route as LayoutRoomsAddRouteImport } from './routes/_layout.rooms.add'
import { Route as LayoutRoomsRoomIdRouteImport } from './routes/_layout.rooms.$roomId'
import { Route as LayoutBookingsMyRouteImport } from './routes/_layout.bookings.my'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoomsRoute = LayoutRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRoomsIndexRoute = LayoutRoomsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoomsRoute,
} as any)
const LayoutBookingsIndexRoute = LayoutBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRoomsAddRoute = LayoutRoomsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => LayoutRoomsRoute,
} as any)
const LayoutRoomsRoomIdRoute = LayoutRoomsRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => LayoutRoomsRoute,
} as any)
const LayoutBookingsMyRoute = LayoutBookingsMyRouteImport.update({
  id: '/bookings/my',
  path: '/bookings/my',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/rooms': typeof LayoutRoomsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/bookings/my': typeof LayoutBookingsMyRoute
  '/rooms/$roomId': typeof LayoutRoomsRoomIdRoute
  '/rooms/add': typeof LayoutRoomsAddRoute
  '/bookings/': typeof LayoutBookingsIndexRoute
  '/rooms/': typeof LayoutRoomsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof LayoutIndexRoute
  '/bookings/my': typeof LayoutBookingsMyRoute
  '/rooms/$roomId': typeof LayoutRoomsRoomIdRoute
  '/rooms/add': typeof LayoutRoomsAddRoute
  '/bookings': typeof LayoutBookingsIndexRoute
  '/rooms': typeof LayoutRoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/rooms': typeof LayoutRoomsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/bookings/my': typeof LayoutBookingsMyRoute
  '/_layout/rooms/$roomId': typeof LayoutRoomsRoomIdRoute
  '/_layout/rooms/add': typeof LayoutRoomsAddRoute
  '/_layout/bookings/': typeof LayoutBookingsIndexRoute
  '/_layout/rooms/': typeof LayoutRoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/rooms'
    | '/auth/callback'
    | '/bookings/my'
    | '/rooms/$roomId'
    | '/rooms/add'
    | '/bookings/'
    | '/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/auth/callback'
    | '/'
    | '/bookings/my'
    | '/rooms/$roomId'
    | '/rooms/add'
    | '/bookings'
    | '/rooms'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/rooms'
    | '/auth/callback'
    | '/_layout/'
    | '/_layout/bookings/my'
    | '/_layout/rooms/$roomId'
    | '/_layout/rooms/add'
    | '/_layout/bookings/'
    | '/_layout/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/rooms': {
      id: '/_layout/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof LayoutRoomsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rooms/': {
      id: '/_layout/rooms/'
      path: '/'
      fullPath: '/rooms/'
      preLoaderRoute: typeof LayoutRoomsIndexRouteImport
      parentRoute: typeof LayoutRoomsRoute
    }
    '/_layout/bookings/': {
      id: '/_layout/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof LayoutBookingsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rooms/add': {
      id: '/_layout/rooms/add'
      path: '/add'
      fullPath: '/rooms/add'
      preLoaderRoute: typeof LayoutRoomsAddRouteImport
      parentRoute: typeof LayoutRoomsRoute
    }
    '/_layout/rooms/$roomId': {
      id: '/_layout/rooms/$roomId'
      path: '/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof LayoutRoomsRoomIdRouteImport
      parentRoute: typeof LayoutRoomsRoute
    }
    '/_layout/bookings/my': {
      id: '/_layout/bookings/my'
      path: '/bookings/my'
      fullPath: '/bookings/my'
      preLoaderRoute: typeof LayoutBookingsMyRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRoomsRouteChildren {
  LayoutRoomsRoomIdRoute: typeof LayoutRoomsRoomIdRoute
  LayoutRoomsAddRoute: typeof LayoutRoomsAddRoute
  LayoutRoomsIndexRoute: typeof LayoutRoomsIndexRoute
}

const LayoutRoomsRouteChildren: LayoutRoomsRouteChildren = {
  LayoutRoomsRoomIdRoute: LayoutRoomsRoomIdRoute,
  LayoutRoomsAddRoute: LayoutRoomsAddRoute,
  LayoutRoomsIndexRoute: LayoutRoomsIndexRoute,
}

const LayoutRoomsRouteWithChildren = LayoutRoomsRoute._addFileChildren(
  LayoutRoomsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutRoomsRoute: typeof LayoutRoomsRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutBookingsMyRoute: typeof LayoutBookingsMyRoute
  LayoutBookingsIndexRoute: typeof LayoutBookingsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutRoomsRoute: LayoutRoomsRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutBookingsMyRoute: LayoutBookingsMyRoute,
  LayoutBookingsIndexRoute: LayoutBookingsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
